# Generated by Django 5.0.3 on 2024-05-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_city_customer_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанный товары'},
        ),
    ]
